name: さんじーえっくすのさくせい

on:
  push:
    branches: [ main ]
jobs:
  build:

    runs-on: ubuntu-latest
    
    container:
      image: pablomk7/libctrpf:0.8.0

    steps:
    - uses: actions/checkout@v4
      
    - name: つくる
      run: make
      
    - name: あげる
      uses: actions/upload-artifact@v4
      with:
        name: out
        path: ./
